name: Deploy to Droplet
env:
  IMAGE_NAME: arzu908/cakey:latest
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone Repository
        uses: actions/checkout@v2
      - name: Login To Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME  }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            export IMAGE_NAME=${{ env.IMAGE_NAME }}
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            docker pull $IMAGE_NAME
            cd test
            docker compose down || true
            docker compose up -d
            docker image prune -f
